student:
  path: /student
  controller: App\Controller\StudentController::index

teacher:
  path: /teacher/{name}
  controller: App\Controller\TeacherController::showTeacher

goToIndex:
  path: /goToIndex
  controller: App\Controller\TeacherController::goToIndex